# general
title: DEVNAESTRADA
email: devnaestrada at gmail com
email_address: contato@devnaestrada.com.br
baseurl: "/"
description: "Podcast sobre front-end, back-end e desenvolvimento web. Venha conhecer o nosso ponto de vista no mundo da programação!"
url: "http://devnaestrada.com.br"

# future posts
future: true

# blog
paginate: 10
paginate_path: "/podcast/:num/"

# service links
services:
  -
    name: "RSS"
    url: "http://bit.ly/dne-rss"
  -
    name: "SoundCloud"
    url: "http://bit.ly/dne-soundcloud"
  -
    name: "Pocket Casts"
    url: "http://bit.ly/dne-pocketcasts"
  -
    name: "iTunes"
    url: "http://bit.ly/dne-itunes"
  -
    name: "Facebook"
    url: "http://bit.ly/dne-facebook"
  -
    name: "Twitter"
    url: "http://bit.ly/dne-twitter"

github_user: "devnaestrada"

# Soundcloud
soundcloud_prefix: "http://feeds.soundcloud.com/stream/"
soundcloud_site_capa: "https://i1.sndcdn.com/avatars-000193055487-kwlygf-t300x300.jpg"

# Google Analytics
google_analytics: UA-63291340-1

# Disqus
disqus_shortname: devnaestrada

# Facebook
facebook_meta: true

# Jekyll build config
markdown: kramdown
jekyll-mentions: https://twitter.com
sass:
  sass_dir: public/assets/scss
  style: compressed

# Required gems
gems:
  - sass
  - jekyll-paginate
  - bourbon